### ISSUE TITLE
Cookie not generated on home page

### ISSUE THREAD

**Issue by Kaway** [Mangalib/mangalib#22]
SF2 FrameworkBundle:Template:template  does not generate a cookie when rendering the page. This cause an exception when trying to log in to the website with the top form.

> exception 'Symfony\Component\Security\Core\Exception\SessionUnavailableException' with message 'Your session has timed out, or you have disabled cookies.' in /home/tenkin/mangashelf/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php:142 Stack trace: #0 /home/tenkin/mangashelf/app/cache/prod/classes.php(105): session_start() #1 /home/tenkin/mangashelf/app/cache/prod/classes.php(169): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #2 /home/tenkin/mangashelf/app/cache/prod/classes.php(481): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 /home/tenkin/mangashelf/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php(77): Symfony\Component\HttpFoundation\Session\Session->get('_security_main') #4 /home/tenkin/mangashelf/app/cache/prod/classes.php(2371): Symfony\Component\Security\Http\Firewall\ContextListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #6 /home/tenkin/mangashelf/app/cache/prod/classes.php(1682): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #7 /home/tenkin/mangashelf/app/cache/prod/classes.php(1615): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #8 /home/tenkin/mangashelf/app/cache/prod/classes.php(1779): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #9 /home/tenkin/mangashelf/app/bootstrap.php.cache(2918): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #10 /home/tenkin/mangashelf/app/bootstrap.php.cache(2903): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /home/tenkin/mangashelf/app/bootstrap.php.cache(3032): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /home/tenkin/mangashelf/app/bootstrap.php.cache(2308): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /home/tenkin/mangashelf/web/app.php(24): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main}

**Comment by Kaway** [comment]
We take the problem by the other side...
On other pages, we display flash message and by checking if there are flash messages, the session is automagically generated. But on this static page, there's no check on flash messages, so the session is not generated. By now, the bug if fixed with a hack, but we need to really fix it by properly creating the session cookie.
<3

**Comment by Kaway** [comment]
Solved.
Session->isStarted() to check if session has been started since symfony 2.1.
